Feature/main screen
agustingodoyc/TheMovieDB pull request #3
Opened 2022-10-18 13:43 UTC by AngelaLee18

STORY
Used coordinator and created Main Screen

DESCRIPTION
Used coordinator to move from splash screen to main screen and designed Now Playing, Top Rated and Upcoming tab with a header "Movies DB" and search icon. 

EVIDENCE

https://user-images.githubusercontent.com/109097550/196446357-73357236-8139-4eb1-ac81-eb0e0c99a30c.mov

<img width="368" alt="Screen Shot 2022-10-18 at 10 41 06" src="https://user-images.githubusercontent.com/109097550/196446408-2df1816e-9feb-4051-a7e9-187c01b2a71f.png">

2022-10-18 15:24 UTC, agustingodoyc approved these changes

2022-10-19 18:56 UTC, RafaBenaGlobant commented
There is some duplicated code between NowPlaying, TopRated and Upcoming VCs Have you considered an alternative?

2022-10-19 20:05 UTC, ezequielvelezglobant requested changes
as @RafaBenaGlobant mentioned there is repetitive code.
Think of a solution and tell us on slack!

2022-10-19 20:05 UTC, ezequielvelezglobant commented on TheMovieDB/TheMovieDB/Presentation/View/Main Screen/TopRatedViewController.swift
> +    }
duplicated code

2022-10-19 20:05 UTC, ezequielvelezglobant commented on TheMovieDB/TheMovieDB/Presentation/View/Main Screen/UpcomingViewController.swift
> +    }
duplicated code

2022-10-20 13:30 UTC, AngelaLee18 commented on TheMovieDB/TheMovieDB/Presentation/View/Main Screen/TopRatedViewController.swift
> +    }
d544b15cef07f5f6da9e8d2b762dd3fb3ef0803c

2022-10-20 13:30 UTC, AngelaLee18 commented on TheMovieDB/TheMovieDB/Presentation/View/Main Screen/UpcomingViewController.swift
> +    }
d544b15cef07f5f6da9e8d2b762dd3fb3ef0803c

2022-10-20 14:14 UTC, AngelaLee18 commented on TheMovieDB/TheMovieDB/Presentation/View/Main Screen/TopRatedViewController.swift
> +    }
187c21c7805f731d3ed2389271edf484eee5ae1b

2022-10-20 14:14 UTC, AngelaLee18 commented on TheMovieDB/TheMovieDB/Presentation/View/Main Screen/UpcomingViewController.swift
> +    }
187c21c7805f731d3ed2389271edf484eee5ae1b

2022-10-20 14:26 UTC, RafaBenaGlobant approved these changes

2022-10-20 15:01 UTC, agustingodoyc approved these changes

2022-10-20 15:14 UTC, ezequielvelezglobant approved these changes

2022-10-20 15:14 UTC, merged